apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Frontend Service</title>
      <style>
        body { font-family: Arial; margin: 40px; background: #f5f5f5; }
        .container { max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 5px; }
        h1 { color: #333; }
        .status { color: green; font-weight: bold; font-size: 18px; }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Frontend Service</h1>
        <p class="status">✓ Running on Nginx (Port 30080)</p>
        <p>Deployed with Kustomize</p>
      </div>
    </body>
    </html>
