---
apiVersion: v1
kind: Namespace
metadata:
  name: sample-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: sample-app
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 32308
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sample-app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Test App -01</title>
    </head>
    <body>
      <h1>Test App Working fine!</h1>
      <p>This application is deployed for testing 01</p>
    </body>
    </html>
