apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: multi-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: multi-service-app
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
