---
apiVersion: v1
kind: Namespace
metadata:
  name: multi-service-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: multi-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: multi-service-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: multi-service-app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Frontend Service</title>
      <style>
        body { font-family: Arial; margin: 40px; background: #f5f5f5; }
        .container { max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 5px; }
        h1 { color: #333; }
        .status { color: green; font-weight: bold; font-size: 18px; }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Frontend Service</h1>
        <p class="status">✓ Running on Nginx (Port 30080)</p>
        <p>This is the public-facing frontend service</p>
        <hr>
        <h3>Services in this deployment:</h3>
        <ul>
          <li>Frontend (Nginx) - You are here</li>
          <li>Backend (httpbin) - Internal API</li>
          <li>Database (Redis) - Data store</li>
        </ul>
      </div>
    </body>
    </html>
