apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multi-service-app

resources:
  - ../../base/frontend
  - ../../base/backend
  - ../../base/database

commonLabels:
  environment: production
  managed-by: kustomize

namePrefix: prod-

replicas:
  - name: frontend
    count: 3
  - name: backend
    count: 3
  - name: database
    count: 1

commonAnnotations:
  deployment-tool: kustomize
  version: "1.0"

images:
  - name: nginx
    newTag: "1.25-alpine"
  - name: kennethreitz/httpbin
    newTag: "latest"
  - name: redis
    newTag: "7-alpine"
